image: registry.gitlab.com/croxis/itf:4.0.2

# NOTE: the `cd` command in each build stage is not necessary if your
# project.godot is at the repo root

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - export
  - deploy

variables:
  EXPORT_NAME: itf

linux:
  stage: export
  script:
    - mkdir -v -p export/linux
    - godot -v --headless --export-debug "Linux/X11" export/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - export/linux

windows:
  stage: export
  script:
    - mkdir -v -p export/windows
    - godot -v --headless --export-debug "Windows Desktop" export/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - export/windows

